{% set name = "nsbm" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fvalle1/trisbm/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6ccf6ddd42d061cd67073ed12ed78465c9cebbcd06523b0e5038b2e3466aa0c4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base
    - pandas
    - cloudpickle
    - graph-tool

test:
  imports:
    - trisbm
  source_files:
    - tests
  commands:
    - python -c "from trisbm import trisbm; model=trisbm()"
    - python tests/run_tests.py

about:
  home: https://github.com/fvalle1/trisbm
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'nSBM, keyword informed topic modeling'
  description: |
    Package to run n-partite Stocastich Block Modeling.
  doc_url: https://fvalle1.github.io/trisbm/
  dev_url: https://github.com/fvalle1/trisbm

extra:
  recipe-maintainers:
    - fvalle1
