{% set name = "nsbm" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fvalle1/trisbm/archive/refs/tags/{{ version }}.tar.gz
  sha256: 20048878395fe4d327c40b1114973c2a4a1c3d62a763f6aae866c3424f2a5968

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base
    - pandas
    - cloudpickle
    - graph-tool

test:
  imports:
    - trisbm
  source_files:
    - tests
  commands:
    - python -c "from nsbm import nsbm; model=nsbm()"
    - python tests/run_tests.py

about:
  home: https://github.com/BioPhys-Turin/nsbm
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: nSBM, keyword informed topic modeling
  description: |
    Package to run n-partite Stocastich Block Modeling.
  doc_url: https://fvalle1.github.io/nsbm/
  dev_url: https://github.com/fvalle1/nsbm

extra:
  recipe-maintainers:
    - fvalle1
